CREATE TABLE IF NOT EXISTS `cctv` (
	`ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`cctvID` VARCHAR(255) NOT NULL UNIQUE,
	`cctv_name` VARCHAR(255),
	`stream_url` VARCHAR(255),
	`screenshot_url` VARCHAR(255),
	`subAuthorityCode` VARCHAR(255),
	`location_type` TINYINT COMMENT '里程位置資訊(enum對應到server)',
	`road_class` TINYINT,
	`road_name` VARCHAR(255),
	`dir` VARCHAR(50),
	`mile` VARCHAR(255),
	`lon` DECIMAL(10,7),
	`lat` DECIMAL(10,7),
	`create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`update_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(`ID`)
);


CREATE INDEX `cctv_index_0`
ON `cctv` (`cctvID`);
CREATE TABLE IF NOT EXISTS `questions` (
	`ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`questionUUID` VARCHAR(255) NOT NULL,
	`gameID` INTEGER UNSIGNED NOT NULL UNIQUE,
	`game_stage` INTEGER NOT NULL,
	`question_cctvID` INTEGER NOT NULL,
	`options` JSON NOT NULL,
	`answerID` INTEGER NOT NULL,
	`user_answerID` INTEGER,
	`elapsed` INTEGER,
	`answer_at` TIMESTAMP,
	`create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`ID`)
);


CREATE TABLE IF NOT EXISTS `games` (
	`ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`gameUUID` VARCHAR(255) UNIQUE,
	`userID` INTEGER UNSIGNED NOT NULL,
	`current_stage` INTEGER,
	`life` INTEGER,
	`total_time` INTEGER,
	`status` ENUM('leaved', 'finish', 'timeout', 'playing') NOT NULL DEFAULT 'playing',
	`finish_at` TIMESTAMP,
	`create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`ID`)
);


CREATE TABLE IF NOT EXISTS `users` (
	`ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255),
	`create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`ID`)
);


ALTER TABLE `questions`
ADD FOREIGN KEY(`question_cctvID`) REFERENCES `cctv`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `questions`
ADD FOREIGN KEY(`gameID`) REFERENCES `games`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `games`
ADD FOREIGN KEY(`userID`) REFERENCES `users`(`ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;